<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>1.0.3</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RepositoryUrl>https://github.com/jh-n/MapIO.git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE" Link="LICENSE" Pack="True" PackagePath="" />
    <None Include="..\..\docs\MapIO.TSK\README.md" Pack="True" PackagePath="" Condition="'$(Targets)' == 'Pack'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\docs\MapIO.TSK\README.md" Pack="True" PackagePath="" Condition="'$(Targets)' != 'Pack'">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MapIO.Core" Version="1.0.4" Condition="'$(Targets)' == 'Pack'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MapIO.Core\MapIO.Core.csproj" Condition="'$(Targets)' != 'Pack'" />
  </ItemGroup>

</Project>
